[FIX] Fix random number gen for UofT
Running `cyvpr.bin.place` on UofT netlists caused errors, such as the
following:

    Traceback (most recent call last):
      File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/home/christian/.virtualenvs/vpr/src/cyvpr/cyvpr/bin/place.py", line 231, in <module>
        place_algorithm=args.place_algorithm, seed=args.seed)
      File "/home/christian/.virtualenvs/vpr/src/cyvpr/cyvpr/bin/place.py", line 99, in place
        fast=fast)
      File "Main.pyx", line 72, in cyvpr.Main.cMain.place (cyvpr/Main.cpp:2094)
    RuntimeError: Bad value in my_irand, imax = 306988  ival = 306989

This commit provides a workaround, which simply retries in such cases until a
valid number is generated.  Note that this shouldn't happen often, and, thus,
should not have an appreciable impact on performance.